import numpy as np

minhaLista = [1,2,3]
print('Vetor')
print(np.array(minhaLista))
minhaMatriz = [[1,2,3],[4,5,6],[7,8,9]]
print('Matriz')
print(np.array(minhaMatriz))
print('Arange cria vetores num range')
print(np.arange(0,15,2))
print('Zeros cria vetor de zeros')
print(np.zeros((5,5)))
print('Cria matriz de 1')
print(np.ones((3,3)))
print('Eyes')
print(np.eye(4))
print('Linspace cria vetor com dados espacados')
print(np.linspace(0,15,5))
print('random rand cria vetor de numeros aleatórios ')
print(np.random.rand(3,3,3))
print('random randn cria vetor de num aleatório não uniformes')
print(np.random.randn(4))
print('random randint cria vetor de num aleatorios inteiros')
print(np.random.randint(0,100,6))
print('reshape transforma um vetor em matriz')
arr = np.random.rand(25)
print('Array criado')
print(arr)
arrRes = arr.reshape((5,5))
print('Array transformado')
print(arrRes)
print('Encontra valor min e seu index no array')
print(arrRes.min())
print(arrRes.argmin())
print('Encontra valor max e seu Index no array')
print(arrRes.max())
print(arrRes.argmax())